/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package whacamole;

import java.awt.Color;

/**
 *
 * @author Aluno
 */
public class Cadastro extends javax.swing.JFrame {

    /** Creates new form Cadastro */
    public Cadastro() {
        initComponents();
        setSize(600,340);
        this.setLocationRelativeTo(null);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        txtUsername = new javax.swing.JTextField();
        txtCpf = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        btnCadastrar = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        pfSenha = new javax.swing.JPasswordField();
        pfRepSenha = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        jLabel2.setText("jLabel2");

        jLabel3.setText("jLabel3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 51));
        setResizable(false);
        setSize(new java.awt.Dimension(600, 300));
        getContentPane().setLayout(null);

        txtNome.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        txtNome.setText("Nome");
        txtNome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtNomeMouseClicked(evt);
            }
        });
        getContentPane().add(txtNome);
        txtNome.setBounds(60, 50, 490, 30);

        txtUsername.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        txtUsername.setText("Username");
        txtUsername.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtUsernameFocusGained(evt);
            }
        });
        getContentPane().add(txtUsername);
        txtUsername.setBounds(60, 90, 490, 30);

        txtCpf.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        txtCpf.setText("CPF");
        txtCpf.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtCpfFocusGained(evt);
            }
        });
        getContentPane().add(txtCpf);
        txtCpf.setBounds(60, 130, 490, 30);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 204, 0));
        jLabel4.setText("Cadastre-se");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(270, 0, 92, 40);

        btnCadastrar.setBackground(new java.awt.Color(255, 255, 204));
        btnCadastrar.setText("Cadastrar");
        btnCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarActionPerformed(evt);
            }
        });
        getContentPane().add(btnCadastrar);
        btnCadastrar.setBounds(260, 240, 92, 30);
        getContentPane().add(jLabel7);
        jLabel7.setBounds(1196, 0, 92, 321);
        getContentPane().add(pfSenha);
        pfSenha.setBounds(60, 200, 230, 30);
        getContentPane().add(pfRepSenha);
        pfRepSenha.setBounds(330, 200, 220, 30);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setText("Senha");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(210, 180, 34, 15);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setText("Repetir Senha");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(350, 180, 80, 15);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/back.PNG"))); // NOI18N
        jLabel8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(jLabel8);
        jLabel8.setBounds(-10, -60, 780, 410);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarActionPerformed
       String nome = txtNome.getText();
       String username = txtUsername.getText();
       String cpf = txtCpf.getText();
       String senha = pfSenha.getText();
       String repSenha = pfRepSenha.getText();
       
       if(senha.equals(repSenha)){
           String query = "INSERT INTO user (nome, username, cpf, password) VALUES ('"+nome+"','"+username+"',"+cpf+",'"+senha+"');";
           System.out.println(query);
           ElJuegoDAO dao = new ElJuegoDAO();
           dao.cadastroUSsuario(query);
           dispose();
           Login log = new Login();
           log.show();
           
       }
    }//GEN-LAST:event_btnCadastrarActionPerformed

    private void txtNomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtNomeMouseClicked
        txtNome.setText("");
    }//GEN-LAST:event_txtNomeMouseClicked

    private void txtUsernameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtUsernameFocusGained
        txtUsername.setText("");
    }//GEN-LAST:event_txtUsernameFocusGained

    private void txtCpfFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCpfFocusGained
        txtCpf.setText("");
    }//GEN-LAST:event_txtCpfFocusGained

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cadastro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCadastrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPasswordField pfRepSenha;
    private javax.swing.JPasswordField pfSenha;
    private javax.swing.JTextField txtCpf;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables

}
