/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package whacamole;

import java.awt.Color;
import java.awt.Graphics;
import java.awt.MouseInfo;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.awt.event.MouseMotionListener;
import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JLabel;
import javax.swing.Timer;
import sun.font.EAttribute;

/**
 *
 * @author Bruno Garcia
 */
public class Cenario extends javax.swing.JPanel implements ActionListener, MouseListener, MouseMotionListener {
    
    private int bolaX, bolaY;
    private float xp0, yp0;
    private Timer timer;
    
    private int xp, yp;

    
    JLabel mousePosition;
    
    EvolutionaryAlgorithm ea = new EvolutionaryAlgorithm(5, 100);
      
    /**
     * Creates new form Cenario
     */
    public Cenario() throws InterruptedException {
        initComponents();
        addMouseListener((MouseListener) this);
        setSize(1000,800);
        bolaX = 445;
        bolaY = 350;
        xp = 445;
        yp = 350;
    }
    
    @Override
    public void paint(Graphics g)
    {
        g.setColor(Color.LIGHT_GRAY);
        g.fillRect(0,0, getWidth(), getHeight());
        g.setColor(Color.red);
        g.fillOval(bolaX, bolaY, 40, 40); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    @Override
    public void actionPerformed(ActionEvent e) {
        /*if(e.getSource() == timer)
        {
            
            bolaX+=dx;
            bolaY+=dy;
            
            if(bolaX<0||bolaX+30>getWidth())
                dx=-dx;
            if(bolaY<0||bolaY+30>getHeight())
                dy=-dy;
            repaint();
        }*/
    }
    
    public void match() throws InterruptedException 
    {
        int i;
        Random rand = new Random();
        for (i=0; i<ea.population.length; i++)
        {
            int directionX = rand.nextInt(1);
            int directionY = rand.nextInt(1);
            if (directionX == 1) {
                bolaX = (int) (xp + ea.population[i][1]);
            } else {
                bolaX = (int) (xp - ea.population[i][1]);
            }
            if (directionY == 1) {
                bolaY = (int) (yp + ea.population[i][2]);
            } else {
                bolaY = (int) (yp - ea.population[i][2]);
            }
            System.out.println(bolaX + " " + bolaY);
            Thread.sleep(1000);
            repaint();
        }
    }
    
    @Override
    public void mouseClicked(MouseEvent e) {
        System.out.println("Mouse clicked at coordinate:" + "[" + e.getX() + "," + e.getY() + "]");
        xp = e.getX();
        yp = e.getY();
        //match(e.getX(), e.getY(), 0.05);
    }

    @Override
    public void mousePressed(MouseEvent e) {
        
    }

    @Override
    public void mouseReleased(MouseEvent e) {
        
    }

    @Override
    public void mouseEntered(MouseEvent e) {
        
    }

    @Override
    public void mouseExited(MouseEvent e) {
        
    }

    @Override
    public void mouseDragged(MouseEvent e) {
        
    }

    @Override
    public void mouseMoved(MouseEvent e) {
        
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
