/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package whacamole;

import java.awt.Color;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Aluno
 */
public class Login extends javax.swing.JFrame {

    /** Creates new form Cadastro */
    public Login() {
        initComponents();
        setSize(600,340);
        this.setLocationRelativeTo(null);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtUsername = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        btnJogar = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        pfSenha = new javax.swing.JPasswordField();
        senha = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 51));
        setPreferredSize(new java.awt.Dimension(600, 300));
        setResizable(false);
        setSize(new java.awt.Dimension(600, 300));
        getContentPane().setLayout(null);

        txtUsername.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        txtUsername.setText("Username");
        txtUsername.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtUsernameMouseClicked(evt);
            }
        });
        getContentPane().add(txtUsername);
        txtUsername.setBounds(180, 160, 250, 30);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 204, 0));
        jLabel4.setText("Login");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(270, 20, 92, 40);

        btnJogar.setBackground(new java.awt.Color(255, 255, 204));
        btnJogar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnJogar.setText("Jogar");
        btnJogar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnJogarActionPerformed(evt);
            }
        });
        getContentPane().add(btnJogar);
        btnJogar.setBounds(260, 270, 92, 30);
        getContentPane().add(jLabel7);
        jLabel7.setBounds(1196, 0, 92, 321);
        getContentPane().add(pfSenha);
        pfSenha.setBounds(180, 220, 250, 30);

        senha.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        senha.setText("Senha");
        getContentPane().add(senha);
        senha.setBounds(260, 200, 80, 16);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/back.PNG"))); // NOI18N
        getContentPane().add(jLabel8);
        jLabel8.setBounds(-20, -40, 800, 410);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnJogarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnJogarActionPerformed
        String query;
        query = "select * from user where username = '" + txtUsername.getText() + "'  AND password = '" + pfSenha.getText() + "' ORDER BY username";
       
        ElJuegoDAO dao = new ElJuegoDAO();
        //Busca para efetuar login
        boolean vef = dao.busca(query);
        //Busca o id do usario para cadastrar como chave estrangeira natabela games --- e necessario chamar busca antes de utilizala
        int idUsuario = dao.id_user;
    
        if(vef == true){
            System.out.println("Login efetuado");
            
            Perfil pf = new Perfil();
            pf.show();
            dispose();
            
        }
        else{
            System.out.println("Falha ao logar");
        }
    }//GEN-LAST:event_btnJogarActionPerformed

    private void txtUsernameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtUsernameMouseClicked
        txtUsername.setText("");
    }//GEN-LAST:event_txtUsernameMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cadastro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnJogar;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPasswordField pfSenha;
    private javax.swing.JLabel senha;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables

}
