/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package whacamole;

import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author lb21-05
 */
public class Perfil extends javax.swing.JFrame {

    /**
     * Creates new form perfil
     */
    public Perfil() {
        initComponents();
        setSize(600,340);
        this.setLocationRelativeTo(null);
        lbJogador.setText(ElJuegoDAO.nome_usuario);
        lbPontuacao.setText(Integer.toString(ElJuegoDAO.pontuacao));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        btnMelhor = new javax.swing.JButton();
        lbJogador = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lbPontuacao = new javax.swing.JLabel();
        btnJogar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 2, 24)); // NOI18N
        jLabel2.setText("Bienvenido");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 20, 120, -1));

        btnMelhor.setText("Melhor jogador");
        btnMelhor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMelhorActionPerformed(evt);
            }
        });
        getContentPane().add(btnMelhor, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 250, 130, -1));

        lbJogador.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbJogador.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbJogador.setText("Jogador");
        getContentPane().add(lbJogador, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 160, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setText("Última Pontuação: ");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 190, -1, -1));

        lbPontuacao.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbPontuacao.setText("00000");
        getContentPane().add(lbPontuacao, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 190, -1, -1));

        btnJogar.setText("Iniciar Partida");
        btnJogar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnJogarActionPerformed(evt);
            }
        });
        getContentPane().add(btnJogar, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 220, 130, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/back.PNG"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, -70, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnMelhorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMelhorActionPerformed
        Best bt = new Best();
        bt.show();
    }//GEN-LAST:event_btnMelhorActionPerformed

    private void btnJogarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnJogarActionPerformed
       //Cadastro da Partida
        String query;
    
        ElJuegoDAO dao = new ElJuegoDAO();
        query = "SELECT * FROM user WHERE id ="+ dao.id_user + "' ORDER BY username";
        
        int idUsuario = dao.id_user;
        String QueryGame = "insert into games (pontuation, id_user) VALUES ("+ 0 +","+ idUsuario +");";
        dao.cadastroPartida(QueryGame);
        
        Game gm;
            try {
                gm = new Game();
                gm.show();
                dispose();
            } catch (InterruptedException ex) {
                System.out.println(ex.getMessage());
            } catch (IOException ex) {
            Logger.getLogger(Perfil.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnJogarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Perfil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Perfil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Perfil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Perfil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Perfil().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnJogar;
    private javax.swing.JButton btnMelhor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lbJogador;
    private javax.swing.JLabel lbPontuacao;
    // End of variables declaration//GEN-END:variables
}
